// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../domain/entities/consultation.dart';
import '../domain/entities/doctor.dart';
import '../domain/entities/patient.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1954417455135903593),
      name: 'Consultation',
      lastPropertyId: const obx_int.IdUid(9, 5853969057493210329),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6981030928349399290),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2185144289833971466),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 591531738265852518),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 144614764880441125),
            name: 'dateTime',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3184513886661190099),
            name: 'duration',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1889245535686007530),
            name: 'value',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 12643732112855530),
            name: 'status',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8585471975098633400),
            name: 'patientId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 5853969057493210329),
            name: 'doctorId',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 6589057988402214074),
      name: 'Doctor',
      lastPropertyId: const obx_int.IdUid(8, 8108134857413526052),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3933818292314874031),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 584467266828027737),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5904526564062833813),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8141261800045809040),
            name: 'photoUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3035628516434095674),
            name: 'phone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6608775942431946362),
            name: 'crfa',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 457308790030943149),
            name: 'specialty',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8108134857413526052),
            name: 'address',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 5894913375927753702),
      name: 'Patient',
      lastPropertyId: const obx_int.IdUid(6, 8333948979212999197),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1684051504906776607),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4230244372338902733),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6613581924477705183),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2921673588245155823),
            name: 'phone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8579281934854708367),
            name: 'cpf',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8333948979212999197),
            name: 'rg',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 5894913375927753702),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Consultation: obx_int.EntityDefinition<Consultation>(
        model: _entities[0],
        toOneRelations: (Consultation object) => [],
        toManyRelations: (Consultation object) => {},
        getId: (Consultation object) => object.id,
        setId: (Consultation object, int id) {
          object.id = id;
        },
        objectToFB: (Consultation object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final descriptionOffset = fbb.writeString(object.description);
          final valueOffset = fbb.writeString(object.value);
          final statusOffset = fbb.writeString(object.status);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addInt64(3, object.dateTime.millisecondsSinceEpoch);
          fbb.addInt64(4, object.duration);
          fbb.addOffset(5, valueOffset);
          fbb.addOffset(6, statusOffset);
          fbb.addInt64(7, object.patientId);
          fbb.addInt64(8, object.doctorId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final dateTimeParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final durationParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final valueParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final statusParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final patientIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final doctorIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 20);
          final object = Consultation(
              id: idParam,
              title: titleParam,
              description: descriptionParam,
              dateTime: dateTimeParam,
              duration: durationParam,
              value: valueParam,
              status: statusParam,
              patientId: patientIdParam,
              doctorId: doctorIdParam);

          return object;
        }),
    Doctor: obx_int.EntityDefinition<Doctor>(
        model: _entities[1],
        toOneRelations: (Doctor object) => [],
        toManyRelations: (Doctor object) => {},
        getId: (Doctor object) => object.id,
        setId: (Doctor object, int id) {
          object.id = id;
        },
        objectToFB: (Doctor object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final emailOffset = fbb.writeString(object.email);
          final photoUrlOffset = object.photoUrl == null
              ? null
              : fbb.writeString(object.photoUrl!);
          final phoneOffset = fbb.writeString(object.phone);
          final crfaOffset = fbb.writeString(object.crfa);
          final specialtyOffset = fbb.writeString(object.specialty);
          final addressOffset = fbb.writeString(object.address);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, photoUrlOffset);
          fbb.addOffset(4, phoneOffset);
          fbb.addOffset(5, crfaOffset);
          fbb.addOffset(6, specialtyOffset);
          fbb.addOffset(7, addressOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final photoUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final phoneParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final crfaParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final specialtyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final addressParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final object = Doctor(
              id: idParam,
              name: nameParam,
              email: emailParam,
              photoUrl: photoUrlParam,
              phone: phoneParam,
              crfa: crfaParam,
              specialty: specialtyParam,
              address: addressParam);

          return object;
        }),
    Patient: obx_int.EntityDefinition<Patient>(
        model: _entities[2],
        toOneRelations: (Patient object) => [],
        toManyRelations: (Patient object) => {},
        getId: (Patient object) => object.id,
        setId: (Patient object, int id) {
          object.id = id;
        },
        objectToFB: (Patient object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final emailOffset = fbb.writeString(object.email);
          final phoneOffset = fbb.writeString(object.phone);
          final cpfOffset =
              object.cpf == null ? null : fbb.writeString(object.cpf!);
          final rgOffset =
              object.rg == null ? null : fbb.writeString(object.rg!);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, phoneOffset);
          fbb.addOffset(4, cpfOffset);
          fbb.addOffset(5, rgOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final phoneParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final cpfParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final rgParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final object = Patient(
              id: idParam,
              name: nameParam,
              email: emailParam,
              phone: phoneParam,
              cpf: cpfParam,
              rg: rgParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Consultation] entity fields to define ObjectBox queries.
class Consultation_ {
  /// See [Consultation.id].
  static final id =
      obx.QueryIntegerProperty<Consultation>(_entities[0].properties[0]);

  /// See [Consultation.title].
  static final title =
      obx.QueryStringProperty<Consultation>(_entities[0].properties[1]);

  /// See [Consultation.description].
  static final description =
      obx.QueryStringProperty<Consultation>(_entities[0].properties[2]);

  /// See [Consultation.dateTime].
  static final dateTime =
      obx.QueryDateProperty<Consultation>(_entities[0].properties[3]);

  /// See [Consultation.duration].
  static final duration =
      obx.QueryIntegerProperty<Consultation>(_entities[0].properties[4]);

  /// See [Consultation.value].
  static final value =
      obx.QueryStringProperty<Consultation>(_entities[0].properties[5]);

  /// See [Consultation.status].
  static final status =
      obx.QueryStringProperty<Consultation>(_entities[0].properties[6]);

  /// See [Consultation.patientId].
  static final patientId =
      obx.QueryIntegerProperty<Consultation>(_entities[0].properties[7]);

  /// See [Consultation.doctorId].
  static final doctorId =
      obx.QueryIntegerProperty<Consultation>(_entities[0].properties[8]);
}

/// [Doctor] entity fields to define ObjectBox queries.
class Doctor_ {
  /// See [Doctor.id].
  static final id =
      obx.QueryIntegerProperty<Doctor>(_entities[1].properties[0]);

  /// See [Doctor.name].
  static final name =
      obx.QueryStringProperty<Doctor>(_entities[1].properties[1]);

  /// See [Doctor.email].
  static final email =
      obx.QueryStringProperty<Doctor>(_entities[1].properties[2]);

  /// See [Doctor.photoUrl].
  static final photoUrl =
      obx.QueryStringProperty<Doctor>(_entities[1].properties[3]);

  /// See [Doctor.phone].
  static final phone =
      obx.QueryStringProperty<Doctor>(_entities[1].properties[4]);

  /// See [Doctor.crfa].
  static final crfa =
      obx.QueryStringProperty<Doctor>(_entities[1].properties[5]);

  /// See [Doctor.specialty].
  static final specialty =
      obx.QueryStringProperty<Doctor>(_entities[1].properties[6]);

  /// See [Doctor.address].
  static final address =
      obx.QueryStringProperty<Doctor>(_entities[1].properties[7]);
}

/// [Patient] entity fields to define ObjectBox queries.
class Patient_ {
  /// See [Patient.id].
  static final id =
      obx.QueryIntegerProperty<Patient>(_entities[2].properties[0]);

  /// See [Patient.name].
  static final name =
      obx.QueryStringProperty<Patient>(_entities[2].properties[1]);

  /// See [Patient.email].
  static final email =
      obx.QueryStringProperty<Patient>(_entities[2].properties[2]);

  /// See [Patient.phone].
  static final phone =
      obx.QueryStringProperty<Patient>(_entities[2].properties[3]);

  /// See [Patient.cpf].
  static final cpf =
      obx.QueryStringProperty<Patient>(_entities[2].properties[4]);

  /// See [Patient.rg].
  static final rg =
      obx.QueryStringProperty<Patient>(_entities[2].properties[5]);
}
